Add request to server
arti1233/Korenko-HM-24- pull request #1
Opened 2022-06-19 17:22 UTC by arti1233

Add request to server and add data object
@vkhadyka

2022-06-19 18:15 UTC, vkhadyka commented on Korenko HM 24/Korenko HM 24/ViewController.swift
> +    let APIKey = "52e0cef2e795eb013506ecb52fb1c280"
I'm not sure that is a good way to store APIKey.
Also `APIKey` variable has wrong name style.

2022-06-19 18:15 UTC, vkhadyka commented on Korenko HM 24/Korenko HM 24/Weather Data .swift
> +//  Weather Data .swift
Try to avoid spaces in filenames.

2022-06-19 18:15 UTC, vkhadyka commented on Korenko HM 24/Korenko HM 24/Weather Data .swift
> +            return "&units=metric"
It's not a bug. just a comment.
`&units=metric` looks good, but it not clear when you read URL request string.
I understand that you have implemented it bcouz `UnitOfMeasurement` has `standart` unit.
One way to do it great, just remove `standart` case and keep others.
It'll be looks great and URL string will read easy.

2022-06-19 19:44 UTC, arti1233 commented
Fixed coments 
@vkhadyka

2022-06-19 20:30 UTC, vkhadyka requested changes
Still spaces in `Korenko HM 24/Korenko HM 24/WeatherData .swift` filename.

2022-06-20 05:23 UTC, vkhadyka approved these changes

2022-06-20 05:23 UTC, merged